DROP TABLE IF EXISTS sprout_students;

CREATE TABLE sprout_students (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  goal TEXT NOT NULL,
  priority TEXT NOT NULL,
  sprout_user_id INTEGER REFERENCES sprout_users(id) NOT NULL
);